version: '3.8'
services:
  app:
    image: webdevops/php-nginx-dev:8.1
    volumes:
      - ..:/workspace:cached
      - /workspace/vendor
    environment:
      - XDEBUG_MODE=off
      - WEB_DOCUMENT_ROOT=/workspace/public
    ports:
      - 8000:80
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
